// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: greet/v1/greet.proto
//
package com.greet.v1

import com.connectrpc.Headers
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.StreamType

public class GreetServiceClient(
  private val client: ProtocolClientInterface,
) : GreetServiceClientInterface {
  override suspend fun greet(request: GreetRequest, headers: Headers): ResponseMessage<GreetResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "greet.v1.GreetService/Greet",
      com.greet.v1.GreetRequest::class,
      com.greet.v1.GreetResponse::class,
      StreamType.UNARY,
    ),
  )

}
