// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: greet/v1/greet.proto
// Protobuf Java Version: 4.33.1

package com.greet.v1;

@com.google.protobuf.Generated
public final class GreetProto extends com.google.protobuf.GeneratedFile {
  private GreetProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "GreetProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_greet_v1_GreetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_greet_v1_GreetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_greet_v1_GreetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_greet_v1_GreetResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024greet/v1/greet.proto\022\010greet.v1\"\"\n\014Gree" +
      "tRequest\022\022\n\004name\030\001 \001(\tR\004name\"+\n\rGreetRes" +
      "ponse\022\032\n\010greeting\030\001 \001(\tR\010greeting2J\n\014Gre" +
      "etService\022:\n\005Greet\022\026.greet.v1.GreetReque" +
      "st\032\027.greet.v1.GreetResponse\"\000B\225\001\n\014com.gr" +
      "eet.v1B\nGreetProtoP\001Z8github.com/example" +
      "/connectrpc-hello/gen/greet/v1;greetv1\242\002" +
      "\003GXX\252\002\010Greet.V1\312\002\010Greet\\V1\342\002\024Greet\\V1\\GP" +
      "BMetadata\352\002\tGreet::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_greet_v1_GreetRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_greet_v1_GreetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_greet_v1_GreetRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_greet_v1_GreetResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_greet_v1_GreetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_greet_v1_GreetResponse_descriptor,
        new java.lang.String[] { "Greeting", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
