// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: greet/v1/greet.proto
// Protobuf Java Version: 4.33.1

package com.greet.v1;

@com.google.protobuf.Generated
public interface GreetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greet.v1.GreetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
