// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: greet/v1/greet.proto
// Protobuf Java Version: 4.33.1

package com.greet.v1;

@com.google.protobuf.Generated
public interface GreetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greet.v1.GreetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1 [json_name = "greeting"];</code>
   * @return The greeting.
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 1 [json_name = "greeting"];</code>
   * @return The bytes for greeting.
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
